=== faberchri/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/client/prototype-input-properties-attBased.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="ch/uzh/agglorecommender/client/inputbeans"
    xmlns:arin="ch/uzh/agglorecommender/client/inputbeans">
    
    <xs:complexType name="File">
        <xs:sequence>
            <xs:element name="ColumnSeparator">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Location" type="xs:string"/>
            <xs:element name="ValueColumnNumber" type="xs:positiveInteger"/>
            <xs:element default="1" minOccurs="0" name="StartLine" type="xs:positiveInteger"/>
            <xs:element default="2147483647" minOccurs="0" name="EndLine" type="xs:positiveInteger"
            />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RatingFile">
        <xs:complexContent>
            <xs:extension base="arin:File">

                <xs:sequence>
                    <xs:element name="UserIdColumnNumber" type="xs:positiveInteger"/>
                    <xs:element name="ContentIdColumnNumber" type="xs:positiveInteger"/>
                    <xs:element name="useForTestOnly" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MetaFile">
        <xs:complexContent>
            <xs:extension base="arin:File">

                <xs:sequence>
                    <xs:element name="IdColumnNumber" type="xs:positiveInteger"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Attribute" abstract="true">
        <xs:sequence>


            <xs:element name="Tag" type="xs:string">
                <xs:unique name="UNIQ_ATT_TAG">
                    <xs:selector xpath="xs:Attribute"/>
                    <xs:field xpath="xs:Tag"/>
                </xs:unique>
            </xs:element>
            <xs:element name="useForClustering" type="xs:boolean"/>
            <xs:element minOccurs="0" name="PreProcessingRegex" type="xs:string"/>
        </xs:sequence>

    </xs:complexType>


    <xs:complexType name="NumericalAttribute">
        <xs:complexContent>
            <xs:extension base="arin:Attribute">

                <xs:sequence>
                    <xs:element name="minValue" type="xs:double"/>
                    <xs:element name="maxValue" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NominalAttribute">
        <xs:complexContent>
            <xs:extension base="arin:Attribute">

                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="Category"
                        type="arin:Category">
                        <xs:unique name="UNIQ_CATEGORY_TAG">
                            <xs:selector xpath="xs:NominalAttribute"/>
                            <xs:field xpath="xs:Categories"/>
                        </xs:unique>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="NominalMultivaluedAttribute">
        <xs:complexContent>
            <xs:extension base="arin:NominalAttribute">

                <xs:sequence>
                    <xs:element name="ValueSeparator" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Category">
        <xs:sequence>
            <xs:element name="CategoryTag" type="xs:string"/>
            <xs:element name="IdentificationRegex" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Input">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" name="Rating">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NumericalAttribute"/>
                            <xs:element name="File" type="arin:RatingFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userNumericalAttribute" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NumericalAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userNominalAttribute" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NominalAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userNominalMultivaluedAttribute" maxOccurs="unbounded"
                    minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NominalMultivaluedAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contentNumericalAttribute" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NumericalAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contentNominalAttribute" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NominalAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contentNominalMultivaluedAttribute" maxOccurs="unbounded"
                    minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Attribute" type="arin:NominalMultivaluedAttribute"/>
                            <xs:element name="File" type="arin:MetaFile" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== faberchri/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/grouplensBig_properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<arin:Input xmlns:arin="ch/uzh/agglorecommender/client/inputbeans"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="ch/uzh/agglorecommender/client/inputbeans file:/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/client/prototype-input-properties-attBased.xsd">
    <arin:Rating>
        <arin:Attribute>
            <arin:Tag>rating</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
            <arin:minValue>0</arin:minValue>
            <arin:maxValue>5</arin:maxValue>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>&#009;</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/u1.test</arin:Location>
            <arin:ValueColumnNumber>3</arin:ValueColumnNumber>
            <arin:UserIdColumnNumber>1</arin:UserIdColumnNumber>
            <arin:ContentIdColumnNumber>2</arin:ContentIdColumnNumber>
            <arin:useForTestOnly>true</arin:useForTestOnly>
        </arin:File>
        <arin:File>
            <arin:ColumnSeparator>&#009;</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/u1.base</arin:Location>
            <arin:ValueColumnNumber>3</arin:ValueColumnNumber>
            <arin:UserIdColumnNumber>1</arin:UserIdColumnNumber>
            <arin:ContentIdColumnNumber>2</arin:ContentIdColumnNumber>
            <arin:useForTestOnly>false</arin:useForTestOnly>
        </arin:File>
    </arin:Rating>
    <arin:userNumericalAttribute>
        <arin:Attribute>
            <arin:Tag>age</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
            <arin:minValue>0</arin:minValue>
            <arin:maxValue>100</arin:maxValue>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/users.dat</arin:Location>
            <arin:ValueColumnNumber>3</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:userNumericalAttribute>
    <arin:userNominalAttribute>
        <arin:Attribute>
            <arin:Tag>sex</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/users.dat</arin:Location>
            <arin:ValueColumnNumber>2</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:userNominalAttribute>
    <arin:userNominalAttribute>
        <arin:Attribute>
            <arin:Tag>occupation</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/users.dat</arin:Location>
            <arin:ValueColumnNumber>4</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:userNominalAttribute>
    <arin:userNominalAttribute>
        <arin:Attribute>
            <arin:Tag>zip code</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
            <arin:Category>
                <arin:CategoryTag>new england</arin:CategoryTag>
                <arin:IdentificationRegex>^0.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>new york</arin:CategoryTag>
                <arin:IdentificationRegex>^1.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>central east cost</arin:CategoryTag>
                <arin:IdentificationRegex>^2.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>south east</arin:CategoryTag>
                <arin:IdentificationRegex>^3.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>rust belt</arin:CategoryTag>
                <arin:IdentificationRegex>^4.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>north central</arin:CategoryTag>
                <arin:IdentificationRegex>^5.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>central central</arin:CategoryTag>
                <arin:IdentificationRegex>^6.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>south central</arin:CategoryTag>
                <arin:IdentificationRegex>^7.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>rocky mountains</arin:CategoryTag>
                <arin:IdentificationRegex>^8.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>west coast</arin:CategoryTag>
                <arin:IdentificationRegex>^9.*</arin:IdentificationRegex>
            </arin:Category>
            <arin:Category>
                <arin:CategoryTag>other</arin:CategoryTag>
                <arin:IdentificationRegex>^\D.*</arin:IdentificationRegex>
            </arin:Category>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/users.dat</arin:Location>
            <arin:ValueColumnNumber>5</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:userNominalAttribute>
    <arin:contentNominalAttribute>
        <arin:Attribute>
            <arin:Tag>title</arin:Tag>
            <arin:useForClustering>0</arin:useForClustering>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/movies.dat</arin:Location>
            <arin:ValueColumnNumber>2</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:contentNominalAttribute>
    <arin:contentNominalMultivaluedAttribute>
        <arin:Attribute>
            <arin:Tag>genre</arin:Tag>
            <arin:useForClustering>1</arin:useForClustering>
            <arin:ValueSeparator>|</arin:ValueSeparator>
        </arin:Attribute>
        <arin:File>
            <arin:ColumnSeparator>+</arin:ColumnSeparator>
            <arin:Location>/Users/faber/Documents/MScPrj/tree-builder-repo/december-19-2012/tree-builder-2/TreeBuilder/src/ch/uzh/agglorecommender/datasets/GrouplensBig/movies.dat</arin:Location>
            <arin:ValueColumnNumber>3</arin:ValueColumnNumber>
            <arin:IdColumnNumber>1</arin:IdColumnNumber>
        </arin:File>
    </arin:contentNominalMultivaluedAttribute>
</arin:Input>
